[theme]
primaryColor = "#6B46C1"  # Purple
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50  # MB

[browser]
gatherUsageStats = false
