[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[server]
# ไม่ต้องกำหนด port สำหรับ Streamlit Cloud
headless = true
enableCORS = false
